In [55]:
# Импорт библиотеки pandas — при выполнении последовательно всех примеров ниже
# импорт выполняется один раз
import pandas as pd 
# Загружаем данные из файла в переменную, создавая объект DataFrame
countries_data = pd.read_csv('data/countries.csv', sep=';') 
# Выгружаем данные из DataFrame в CSV-файл и сохраняем файл в папке data
countries_data.to_csv('data/countries.txt', index=False, sep=' ')

In [56]:
# Загружаем данные из файла в переменную, создавая объект DataFrame
txt_df = pd.read_table('data/countries.txt', sep=' ', index_col=['country'])
# Выводим содержимое DataFrame на экран
display(txt_df)

           population    square
country
Англия          56.29    133396
Канада          38.05   9984670
США            322.28   9826630
Россия         146.24  17125191
Украина         45.50    603628
Беларусь         9.50    207600
Казахстан       17.04   2724902

In [57]:
# Загружаем данные из файла в переменную, создавая объект DataFrame
melb_data = pd.read_csv('data/melb_data_ps.csv', header=None) 
# Выводим содержимое DataFrame на экран
display(melb_data)

,0,1,2,3,4,5,6,7,8,9,...,13,14,15,16,17,18,19,20,21,22
0,index,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount,Coordinates
1,0,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1,202.0,126.0,1970,Yarra,-37.7996,144.9984,Northern Metropolitan,4019,"-37.7996, 144.9984"
2,1,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,0,156.0,79.0,1900,Yarra,-37.8079,144.9934,Northern Metropolitan,4019,"-37.8079, 144.9934"
3,2,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,0,134.0,150.0,1900,Yarra,-37.8093,144.9944,Northern Metropolitan,4019,"-37.8093, 144.9944"
4,3,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,1,94.0,126.0,1970,Yarra,-37.7969,144.9969,Northern Metropolitan,4019,"-37.7969, 144.9969"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13576,13575,Wheelers Hill,12 Strada Cr,4,h,1245000.0,S,Barry,26/08/2017,16.7,...,2,652.0,126.0,1981,NaN,-37.90562,145.16761,South-Eastern Metropolitan,7392,"-37.90562, 145.16761"
13577,13576,Williamstown,77 Merrett Dr,3,h,1031000.0,SP,Williams,26/08/2017,6.8,...,2,333.0,133.0,1995,NaN,-37.85927,144.87904,Western Metropolitan,6380,"-37.85927, 144.87904"
13578,13577,Williamstown,83 Power St,3,h,1170000.0,S,Raine,26/08/2017,6.8,...,4,436.0,126.0,1997,NaN,-37.85274,144.88738,Western Metropolitan,6380,"-37.85274, 144.88738"
13579,13578,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,...,5,866.0,157.0,1920,NaN,-37.85908,144.89299,Western Metropolitan,6380,"-37.85908, 144.89299"
13580,13579,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,...,1,362.0,112.0,1920,NaN,-37.81188,144.88449,Western Metropolitan,6543,"-37.81188, 144.88449"

In [58]:
# Считываем данные из файла с неизвестной кодировкой в переменную, создавая объект DataFrame
data=pd.read_csv('data/ErrorEnCoding.csv', header=None, encoding_errors='replace') 
# Выводим содержимое DataFrame на экран
display(data)

            0                           1             2
0   User_943         Accumanst@gmail.com         ������
1   User_908           Advismowr@mail.ru         ������
2   User_962             Anachso@ukr.net      ���������
3   User_973            Antecia@inbox.ru          �����
4   User_902          Balliaryva@ukr.net
..        ...                         ...           ...
95  User_959    UpdatesCurious@yahoo.com         ������
96  User_901          V2artierso@mail.ru    �����������
97  User_970            Vashoterlo@bk.ru        �������
98  User_965         Visuareda@yahoo.com        �������
99  User_921                Aavast@ya.ru         ������

[100 rows x 3 columns]

In [59]:
# Импортируем субмодуль chardet.universal
from chardet.universaldetector import UniversalDetector

detector = UniversalDetector()

with open('data/ErrorEnCoding.csv', 'rb') as fh:
    for line in fh:
        detector.feed(line)
        if detector.done:
            break
print(detector.close())

{'encoding': 'KOI8-R', 'confidence': 0.8773902118791048, 'language': 'Russian'}

In [60]:
# Создаем DataFrame из файла, явно указав кодировку символов, и выводим его содержимое на экран
data=pd.read_csv('data/ErrorEnCoding.csv', encoding='koi8-r', header=None)
display(data)

            0                           1             2
0   User_943         Accumanst@gmail.com         Ижевск
1   User_908           Advismowr@mail.ru         Ижевск
2   User_962             Anachso@ukr.net      Краснодар
3   User_973            Antecia@inbox.ru          Пермь
4   User_902          Balliaryva@ukr.net
..        ...                         ...           ...
95  User_959    UpdatesCurious@yahoo.com         Тюмень
96  User_901          V2artierso@mail.ru    Арзангелтск
97  User_970            Vashoterlo@bk.ru        Воронеж
98  User_965         Visuareda@yahoo.com        Воронеж
99  User_921                Aavast@ya.ru         Ижевск

[100 rows x 3 columns]

In [61]:
# Загружаем данные из файла в переменную, создавая объект DataFrame
df = pd.read_table('data/melb_data.csv', sep=',')
# Выводим содержимое DataFrame на экран
display(df)

,Unnamed: 0,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,3/12/2016,2.5,...,1.0,1.0,202.0,NaN,NaN,Yarra,-37.79960,144.99840,Northern Metropolitan,4019.0
1,2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,4/02/2016,2.5,...,1.0,0.0,156.0,79.0,1900.0,Yarra,-37.80790,144.99340,Northern Metropolitan,4019.0
2,4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,4/03/2017,2.5,...,2.0,0.0,134.0,150.0,1900.0,Yarra,-37.80930,144.99440,Northern Metropolitan,4019.0
3,5,Abbotsford,40 Federation La,3,h,850000.0,PI,Biggin,4/03/2017,2.5,...,2.0,1.0,94.0,NaN,NaN,Yarra,-37.79690,144.99690,Northern Metropolitan,4019.0
4,6,Abbotsford,55a Park St,4,h,1600000.0,VB,Nelson,4/06/2016,2.5,...,1.0,2.0,120.0,142.0,2014.0,Yarra,-37.80720,144.99410,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18391,23540,Williamstown,8/2 Thompson St,2,t,622500.0,SP,Greg,26/08/2017,6.8,...,2.0,1.0,NaN,89.0,2010.0,NaN,-37.86393,144.90484,Western Metropolitan,6380.0
18392,23541,Williamstown,96 Verdon St,4,h,2500000.0,PI,Sweeney,26/08/2017,6.8,...,1.0,5.0,866.0,157.0,1920.0,NaN,-37.85908,144.89299,Western Metropolitan,6380.0
18393,23544,Yallambie,17 Amaroo Wy,4,h,1100000.0,S,Buckingham,26/08/2017,12.7,...,3.0,2.0,NaN,NaN,NaN,NaN,-37.72006,145.10547,Northern Metropolitan,1369.0
18394,23545,Yarraville,6 Agnes St,4,h,1285000.0,SP,Village,26/08/2017,6.3,...,1.0,1.0,362.0,112.0,1920.0,NaN,-37.81188,144.88449,Western Metropolitan,6543.0
18395,23546,Yarraville,33 Freeman St,4,h,1050000.0,VB,Village,26/08/2017,6.3,...,2.0,2.0,NaN,139.0,1950.0,NaN,-37.81829,144.87404,Western Metropolitan,6543.0

In [62]:
data = pd.read_csv('data/students_performance.zip')
display(data)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [63]:
# Определяем параметры архивирования — метод сжатия, имя файла в архиве
compression_opts = dict(method='zip', archive_name='out.csv') 
data.to_csv('data/out.zip', index=False, compression=compression_opts)

In [64]:
grades = pd.read_excel('data/grades.xlsx')
display(grades.head())

   Student ID Student name  Grade
0           1          Аня      8
1           2         Катя      9
2           3         Маша      7
3           4         Миша      4
4           5         Женя      8

In [65]:
data = pd.read_excel('data/january.xlsx', skiprows=3)
display(data)

      Location  Oranges  Apples  Bananas  Blueberries  Total
0      Toronto     7651    4422     8580         3679  24332
1  Los Angeles      273    2998     9890         7293  20454
2      Atlanta     3758    6752     4599         4149  19258
3     New York     4019    8796     8486         9188  30489

In [66]:
grades = pd.read_excel('data/grades.xlsx', sheet_name='ML')
display(grades.head())

   Student ID Student name  Grade
0           1          Аня      7
1           2         Катя      5
2           3         Маша      9
3           4         Миша      8
4           5         Женя      9

In [67]:
# Сохраняем данные из DataFrame grades в файл grades_new.xlsx (на листе 'Example') в папке data
grades.to_excel('data/grades_new.xlsx', sheet_name='Example', index=False)

In [68]:


# Чтение Excel-файла
excel_file = 'data/ratings_movies.xlsx'

# Получение названий листов
sheet_names = pd.ExcelFile(excel_file).sheet_names

# Чтение двух листов
df1 = pd.read_excel(excel_file, sheet_name=sheet_names[0])
df2 = pd.read_excel(excel_file, sheet_name=sheet_names[1])

# Объединение
df_combined = pd.concat([df1, df2], ignore_index=True)

# Сохранение в новый файл
output_file = 'combined_data.csv'
df_combined.to_csv(output_file, index=False)

# Подсчёт строк, включая заголовок
total_lines = len(df_combined) + 1
print("Всего строк (с заголовком):", total_lines)

Всего строк (с заголовком): 110579

In [69]:
import json

# Открываем файл и связываем его с объектом "f"
with open('data/recipes.json') as f:  
    # Загружаем содержимое открытого файла в переменную recipes  
    recipes = json.load(f)

In [70]:
from pprint import pprint

# Выводим на экран содержимое переменной recipes, используя функцию pprint()
pprint(recipes)

[{'cuisine': 'greek',
  'id': 10259,
  'ingredients': ['romaine lettuce',
                  'black olives',
                  'grape tomatoes',
                  'garlic',
                  'pepper',
                  'purple onion',
                  'seasoning',
                  'garbanzo beans',
                  'feta cheese crumbles']},
 {'cuisine': 'southern_us',
  'id': 25693,
  'ingredients': ['plain flour',
                  'ground pepper',
                  'salt',
                  'tomatoes',
                  'ground black pepper',
                  'thyme',
                  'eggs',
                  'green tomatoes',
                  'yellow corn meal',
                  'milk',
                  'vegetable oil']},
 {'cuisine': 'filipino',
  'id': 20130,
  'ingredients': ['eggs',
                  'pepper',
                  'salt',
                  'mayonaise',
                  'cooking oil',
                  'green chilies',
                  'grilled chicken breasts',
                  'garlic powder',
                  'yellow onion',
                  'soy sauce',
                  'butter',
                  'chicken livers']},
 {'cuisine': 'indian',
  'id': 22213,
  'ingredients': ['water', 'vegetable oil', 'wheat', 'salt']},
 {'cuisine': 'indian',
  'id': 13162,
  'ingredients': ['black pepper',
                  'shallots',
                  'cornflour',
                  'cayenne pepper',
                  'onions',
                  'garlic paste',
                  'milk',
                  'butter',
                  'salt',
                  'lemon juice',
                  'water',
                  'chili powder',
                  'passata',
                  'oil',
                  'ground cumin',
                  'boneless chicken skinless thigh',
                  'garam masala',
                  'double cream',
                  'natural yogurt',
                  'bay leaf']},
 {'cuisine': 'jamaican',
  'id': 6602,
  'ingredients': ['plain flour',
                  'sugar',
                  'butter',
                  'eggs',
                  'fresh ginger root',
                  'salt',
                  'ground cinnamon',
                  'milk',
                  'vanilla extract',
                  'ground ginger',
                  'powdered sugar',
                  'baking powder']},
 {'cuisine': 'spanish',
  'id': 42779,
  'ingredients': ['olive oil',
                  'salt',
                  'medium shrimp',
                  'pepper',
                  'garlic',
                  'chopped cilantro',
                  'jalapeno chilies',
                  'flat leaf parsley',
                  'skirt steak',
                  'white vinegar',
                  'sea salt',
                  'bay leaf',
                  'chorizo sausage']},
 {'cuisine': 'italian',
  'id': 3735,
  'ingredients': ['sugar',
                  'pistachio nuts',
                  'white almond bark',
                  'flour',
                  'vanilla extract',
                  'olive oil',
                  'almond extract',
                  'eggs',
                  'baking powder',
                  'dried cranberries']},
 {'cuisine': 'mexican',
  'id': 16903,
  'ingredients': ['olive oil',
                  'purple onion',
                  'fresh pineapple',
                  'pork',
                  'poblano peppers',
                  'corn tortillas',
                  'cheddar cheese',
                  'ground black pepper',
                  'salt',
                  'iceberg lettuce',
                  'lime',
                  'jalapeno chilies',
                  'chopped cilantro fresh']},
 {'cuisine': 'italian',
  'id': 12734,
  'ingredients': ['chopped tomatoes',
                  'fresh basil',
                  'garlic',
                  'extra-virgin olive oil',
                  'kosher salt',
                  'flat leaf parsley']},
 {'cuisine': 'italian',
  'id': 5875,
  'ingredients': ['pimentos',
                  'sweet pepper',
                  'dried oregano',
                  'olive oil',
                  'garlic',
                  'sharp cheddar cheese',
                  'pepper',
                  'swiss cheese',
                  'provolone cheese',
                  'canola oil',
                  'mushrooms',
                  'black olives',
                  'sausages']},
 {'cuisine': 'chinese',
  'id': 45887,
  'ingredients': ['low sodium soy sauce',
                  'fresh ginger',
                  'dry mustard',
                  'green beans',
                  'white pepper',
                  'sesame oil',
                  'scallions',
                  'canola oil',
                  'sugar',
                  'Shaoxing wine',
                  'garlic',
                  'ground turkey',
                  'water',
                  'crushed red pepper flakes',
                  'corn starch']},
 {'cuisine': 'italian',
  'id': 2698,
  'ingredients': ['Italian parsley leaves',
                  'walnuts',
                  'hot red pepper flakes',
                  'extra-virgin olive oil',
                  'fresh lemon juice',
                  'trout fillet',
                  'garlic cloves',
                  'chipotle chile',
                  'fine sea salt',
                  'flat leaf parsley']},
 {'cuisine': 'mexican',
  'id': 41995,
  'ingredients': ['ground cinnamon',
                  'fresh cilantro',
                  'chili powder',
                  'ground coriander',
                  'kosher salt',
                  'ground black pepper',
                  'garlic',
                  'plum tomatoes',
                  'avocado',
                  'lime juice',
                  'flank steak',
                  'salt',
                  'ground cumin',
                  'black pepper',
                  'olive oil',
                  'crushed red pepper flakes',
                  'onions']},
 {'cuisine': 'italian',
  'id': 31908,
  'ingredients': ['fresh parmesan cheese',
                  'butter',
                  'all-purpose flour',
                  'fat free less sodium chicken broth',
                  'chopped fresh chives',
                  'gruyere cheese',
                  'ground black pepper',
                  'bacon slices',
                  'gnocchi',
                  'fat free milk',
                  'cooking spray',
                  'salt']},
 {'cuisine': 'indian',
  'id': 24717,
  'ingredients': ['tumeric',
                  'vegetable stock',
                  'tomatoes',
                  'garam masala',
                  'naan',
                  'red lentils',
                  'red chili peppers',
                  'onions',
                  'spinach',
                  'sweet potatoes']},
 {'cuisine': 'british',
  'id': 34466,
  'ingredients': ['greek yogurt',
                  'lemon curd',
                  'confectioners sugar',
                  'raspberries']},
 {'cuisine': 'italian',
  'id': 1420,
  'ingredients': ['italian seasoning',
                  'broiler-fryer chicken',
                  'mayonaise',
                  'zesty italian dressing']},
 {'cuisine': 'thai',
  'id': 2941,
  'ingredients': ['sugar', 'hot chili', 'asian fish sauce', 'lime juice']},
 {'cuisine': 'vietnamese',
  'id': 8152,
  'ingredients': ['soy sauce',
                  'vegetable oil',
                  'red bell pepper',
                  'chicken broth',
                  'yellow squash',
                  'garlic chili sauce',
                  'sliced green onions',
                  'broccolini',
                  'salt',
                  'fresh lime juice',
                  'cooked rice',
                  'chicken breasts',
                  'corn starch']},
 {'cuisine': 'thai',
  'id': 13121,
  'ingredients': ['pork loin',
                  'roasted peanuts',
                  'chopped cilantro fresh',
                  'hoisin sauce',
                  'creamy peanut butter',
                  'chopped fresh mint',
                  'thai basil',
                  'rice',
                  'medium shrimp',
                  'water',
                  'rice noodles',
                  'beansprouts']},
 {'cuisine': 'mexican',
  'id': 40523,
  'ingredients': ['roma tomatoes',
                  'kosher salt',
                  'purple onion',
                  'jalapeno chilies',
                  'lime',
                  'chopped cilantro']},
 {'cuisine': 'southern_us',
  'id': 40989,
  'ingredients': ['low-fat mayonnaise',
                  'pepper',
                  'salt',
                  'baking potatoes',
                  'eggs',
                  'spicy brown mustard']},
 {'cuisine': 'chinese',
  'id': 29630,
  'ingredients': ['sesame seeds',
                  'red pepper',
                  'yellow peppers',
                  'water',
                  'extra firm tofu',
                  'broccoli',
                  'soy sauce',
                  'orange bell pepper',
                  'arrowroot powder',
                  'fresh ginger',
                  'sesame oil',
                  'red curry paste']},
 {'cuisine': 'italian',
  'id': 49136,
  'ingredients': ['marinara sauce',
                  'flat leaf parsley',
                  'olive oil',
                  'linguine',
                  'capers',
                  'crushed red pepper flakes',
                  'olives',
                  'lemon zest',
                  'garlic']},
 {'cuisine': 'chinese',
  'id': 26705,
  'ingredients': ['sugar',
                  'lo mein noodles',
                  'salt',
                  'chicken broth',
                  'light soy sauce',
                  'flank steak',
                  'beansprouts',
                  'dried black mushrooms',
                  'pepper',
                  'chives',
                  'oyster sauce',
                  'dark soy sauce',
                  'peanuts',
                  'sesame oil',
                  'cabbage']},
 {'cuisine': 'cajun_creole',
  'id': 27976,
  'ingredients': ['herbs',
                  'lemon juice',
                  'fresh tomatoes',
                  'paprika',
                  'mango',
                  'stock',
                  'chile pepper',
                  'onions',
                  'red chili peppers',
                  'oil']},
 {'cuisine': 'italian',
  'id': 22087,
  'ingredients': ['ground black pepper',
                  'butter',
                  'sliced mushrooms',
                  'sherry',
                  'salt',
                  'grated parmesan cheese',
                  'heavy cream',
                  'spaghetti',
                  'chicken broth',
                  'cooked chicken',
                  'all-purpose flour']},
 {'cuisine': 'chinese',
  'id': 9197,
  'ingredients': ['green bell pepper',
                  'egg roll wrappers',
                  'sweet and sour sauce',
                  'corn starch',
                  'molasses',
                  'vegetable oil',
                  'oil',
                  'soy sauce',
                  'shredded cabbage',
                  'garlic',
                  'onions',
                  'fresh ginger root',
                  'ground pork',
                  'carrots']},
 {'cuisine': 'mexican',
  'id': 1299,
  'ingredients': ['flour tortillas',
                  'cheese',
                  'breakfast sausages',
                  'large eggs']},
 {'cuisine': 'italian',
  'id': 40429,
  'ingredients': ['yellow corn meal',
                  'boiling water',
                  'butter',
                  'fresh parmesan cheese',
                  'sea salt']},
 {'cuisine': 'cajun_creole',
  'id': 34419,
  'ingredients': ['chicken broth',
                  'chicken breasts',
                  'hot sauce',
                  'red bell pepper',
                  'potatoes',
                  'bacon',
                  'garlic cloves',
                  'fresh parsley',
                  'andouille sausage',
                  'cajun seasoning',
                  'peanut oil',
                  'celery',
                  'ground red pepper',
                  'all-purpose flour',
                  'shrimp',
                  'onions']},
 {'cuisine': 'mexican',
  'id': 10276,
  'ingredients': ['chili powder',
                  'crushed red pepper flakes',
                  'garlic powder',
                  'sea salt',
                  'ground cumin',
                  'onion powder',
                  'dried oregano',
                  'ground black pepper',
                  'paprika']},
 {'cuisine': 'thai',
  'id': 33465,
  'ingredients': ['eggs',
                  'shallots',
                  'firm tofu',
                  'beansprouts',
                  'turnips',
                  'palm sugar',
                  'vegetable oil',
                  'garlic cloves',
                  'sliced chicken',
                  'fish sauce',
                  'lime wedges',
                  'roasted peanuts',
                  'green papaya',
                  'chile powder',
                  'ground black pepper',
                  'tamarind paste',
                  'chinese chives']},
 {'cuisine': 'italian',
  'id': 39250,
  'ingredients': ['olive oil',
                  'onions',
                  'crushed garlic',
                  'dried oregano',
                  'green onions',
                  'white sugar',
                  'dried basil',
                  'diced tomatoes']},
 {'cuisine': 'cajun_creole',
  'id': 37963,
  'ingredients': ['olive oil',
                  'diced tomatoes',
                  'Johnsonville Andouille Dinner Sausage',
                  'parsley',
                  'shrimp',
                  'jambalaya rice mix',
                  'worcestershire sauce',
                  'hot pepper sauce',
                  'creole seasoning']},
 {'cuisine': 'italian',
  'id': 20051,
  'ingredients': ['olive oil',
                  'bread slices',
                  'great northern beans',
                  'garlic cloves',
                  'pepper',
                  'shrimp',
                  'sage leaves',
                  'salt']},
 {'cuisine': 'filipino',
  'id': 11300,
  'ingredients': ['chicken broth',
                  'cooking oil',
                  'chinese five-spice powder',
                  'ground black pepper',
                  'salt',
                  'sugar',
                  'crushed garlic',
                  'chicken thighs',
                  'soy sauce',
                  'star anise']},
 {'cuisine': 'southern_us',
  'id': 17610,
  'ingredients': ['green onions',
                  'cream cheese',
                  'shredded cheddar cheese',
                  'cayenne pepper',
                  'chili powder',
                  'garlic cloves',
                  'black-eyed peas',
                  'tortilla chips']},
 {'cuisine': 'southern_us',
  'id': 37405,
  'ingredients': ['collard greens',
                  'extra-virgin olive oil',
                  'ham hock',
                  'chicken stock',
                  'apple cider',
                  'freshly ground pepper',
                  'chile powder',
                  'bay leaves',
                  'salt',
                  'rib',
                  'light brown sugar',
                  'large garlic cloves',
                  'cayenne pepper',
                  'onions']},
 {'cuisine': 'italian',
  'id': 28302,
  'ingredients': ['Oscar Mayer Deli Fresh Smoked Ham',
                  'hoagie rolls',
                  'salami',
                  'giardiniera',
                  'mozzarella cheese',
                  'pepperoni',
                  'butter',
                  'italian seasoning']},
 {'cuisine': 'brazilian',
  'id': 31634,
  'ingredients': ['ice cubes', 'club soda', 'white rum', 'lime', 'turbinado']},
 {'cuisine': 'mexican',
  'id': 32304,
  'ingredients': ['cooked chicken',
                  'enchilada sauce',
                  'sliced green onions',
                  'picante sauce',
                  'green pepper',
                  'corn tortillas',
                  'canned black beans',
                  'shredded lettuce',
                  'sour cream',
                  'shredded cheddar cheese',
                  'garlic cloves',
                  'canola oil']},
 {'cuisine': 'indian',
  'id': 36341,
  'ingredients': ['salmon fillets',
                  'shallots',
                  'cumin seed',
                  'fresh cilantro',
                  'salt',
                  'curry powder',
                  'vegetable oil',
                  'serrano chile',
                  'fresh ginger',
                  'sauce']},
 {'cuisine': 'mexican',
  'id': 29369,
  'ingredients': ['tomatoes',
                  'chicken breast halves',
                  'chopped cilantro fresh',
                  'white vinegar',
                  'jalapeno chilies',
                  'salt',
                  'black pepper',
                  'vegetable oil',
                  'avocado',
                  'lettuce leaves',
                  'chopped onion']},
 {'cuisine': 'chinese',
  'id': 27564,
  'ingredients': ['eggs',
                  'mandarin oranges',
                  'water',
                  'orange liqueur',
                  'yellow cake mix',
                  'frosting',
                  'vegetable oil',
                  'white sugar']},
 {'cuisine': 'french',
  'id': 18515,
  'ingredients': ['sugar',
                  'salt',
                  'fennel bulb',
                  'water',
                  'lemon olive oil',
                  'grapefruit juice']},
 {'cuisine': 'southern_us',
  'id': 3335,
  'ingredients': ['sugar',
                  'all-purpose flour',
                  'vegetable oil',
                  'white cornmeal',
                  'baking powder',
                  'onions',
                  'bacon drippings',
                  'buttermilk']},
 {'cuisine': 'southern_us',
  'id': 4499,
  'ingredients': ['butter',
                  'crab boil',
                  'garlic',
                  'old bay seasoning',
                  'cream cheese',
                  'crawfish',
                  'salt']},
 {'cuisine': 'southern_us',
  'id': 4906,
  'ingredients': ['mayonaise',
                  'white sugar',
                  'ground black pepper',
                  'salt',
                  'white vinegar',
                  'lemon juice']},
 {'cuisine': 'japanese',
  'id': 5767,
  'ingredients': ['sirloin',
                  'mirin',
                  'yellow onion',
                  'low sodium soy sauce',
                  'water',
                  'corn oil',
                  'sugar',
                  'green onions',
                  'glass noodles',
                  'sake',
                  'shiitake',
                  'napa cabbage']},
 {'cuisine': 'southern_us',
  'id': 30748,
  'ingredients': ['large eggs',
                  'whipping cream',
                  'chicken broth',
                  'ground red pepper',
                  'extra sharp cheddar cheese',
                  'quickcooking grits',
                  'hot sauce',
                  'ground black pepper',
                  'worcestershire sauce',
                  'monterey jack']},
 {'cuisine': 'italian',
  'id': 35930,
  'ingredients': ['fresh basil',
                  'bay leaves',
                  'crushed red pepper',
                  'mussels',
                  'olive oil',
                  'basil',
                  'garlic cloves',
                  'black pepper',
                  'dry white wine',
                  'salt',
                  'tomatoes',
                  'finely chopped onion',
                  'linguine',
                  'flat leaf parsley']},

In [71]:
# Количество ингредиентов в первом блюде
print(len(recipes[0]['ingredients']))

9

In [72]:
for recipe in recipes:
    if recipe.get("id") == 13121:
        from pprint import pprint
        pprint(recipe)
        break

{'cuisine': 'thai',
 'id': 13121,
 'ingredients': ['pork loin',
                 'roasted peanuts',
                 'chopped cilantro fresh',
                 'hoisin sauce',
                 'creamy peanut butter',
                 'chopped fresh mint',
                 'thai basil',
                 'rice',
                 'medium shrimp',
                 'water',
                 'rice noodles',
                 'beansprouts']}

In [73]:
unique_cuisines = []

for recipe in recipes:
    cuisine = recipe.get("cuisine")
    if cuisine and cuisine not in unique_cuisines:
        unique_cuisines.append(cuisine)

print(f"Количество уникальных кухонь: {len(unique_cuisines)}")
print("Список кухонь:", unique_cuisines)

Количество уникальных кухонь: 20
Список кухонь: ['greek', 'southern_us', 'filipino', 'indian', 'jamaican', 'spanish', 'italian', 'mexican', 'chinese', 'british', 'thai', 'vietnamese', 'cajun_creole', 'brazilian', 'french', 'japanese', 'irish', 'korean', 'moroccan', 'russian']

In [74]:
# Словарь для хранения количества рецептов на каждую кухню
cuisine_counts = {}

# Проходим по каждой уникальной кухне
for cuisine in unique_cuisines:
    count = 0
    for recipe in recipes:
        if recipe.get("cuisine") == cuisine:
            count += 1
    cuisine_counts[cuisine] = count

# Находим кухню с максимальным числом рецептов
most_common_cuisine = max(cuisine_counts, key=cuisine_counts.get)
max_count = cuisine_counts[most_common_cuisine]

print(f"Больше всего рецептов принадлежит кухне: {most_common_cuisine}")
print(f"Количество рецептов: {max_count}")

Больше всего рецептов принадлежит кухне: italian
Количество рецептов: 101

In [75]:
# Создаём объект DataFrame из списка recipes
df = pd.DataFrame(recipes) 
# Выводим на экран первые строки полученного DataFrame
display(df.head())

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...

In [76]:
# Импортируем модуль pandas
import pandas as pd 
# Создаём объект DataFrame, загружая содержимое файла recipes.json
df = pd.read_json('data/recipes.json') 

# Выводим на экран первые строки полученного DataFrame
display(df.head())

      id      cuisine                                        ingredients
0  10259        greek  [romaine lettuce, black olives, grape tomatoes...
1  25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2  20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3  22213       indian                [water, vegetable oil, wheat, salt]
4  13162       indian  [black pepper, shallots, cornflour, cayenne pe...

In [77]:
df

        id      cuisine                                        ingredients
0    10259        greek  [romaine lettuce, black olives, grape tomatoes...
1    25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2    20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3    22213       indian                [water, vegetable oil, wheat, salt]
4    13162       indian  [black pepper, shallots, cornflour, cayenne pe...
..     ...          ...                                                ...
495   1121      chinese  [ground pepper, garlic, safflower oil, green o...
496  18376      italian  [penne, garlic, eggplant, lemon juice, olive o...
497  17815      italian  [cold water, dry white wine, fish fillets, cho...
498  32878  southern_us  [water, cajun seasoning, yellow onion, shrimp,...
499  24410      british  [mint, large eggs, heavy cream, berries, groun...

[500 rows x 3 columns]

In [78]:
all_ingredients = set()

for ingredients_list in df['ingredients']:
    all_ingredients.update(ingredients_list)

ingredient_list = sorted(all_ingredients)

In [79]:
all_ingredients

{'cheese tortellini',
 'tomato ketchup',
 'cheese slices',
 'kahlГєa',
 'cajun seasoning',
 'pasta water',
 'mango',
 'bird chile',
 'nonfat milk',
 'italian seasoning',
 'lean ground pork',
 'uncooked rigatoni',
 'chopped fresh mint',
 'stock',
 'shrimp',
 'chopped walnuts',
 'sheepвЂ™s milk cheese',
 'phyllo',
 'chicken tenderloin',
 'rib',
 'chicken wings',
 'mini cucumbers',
 'thai chile',
 'eggs',
 'persian cucumber',
 'branzino fillets',
 'prepared horseradish',
 'brown mustard seeds',
 'lemon zest',
 'matcha green tea powder',
 'burger buns',
 'corn kernels',
 'kosher salt',
 'coriander',
 'food colouring',
 'store bought low sodium chicken stock',
 'dried kidney beans',
 'karashi',
 'part-skim ricotta cheese',
 'white cornmeal',
 'Korean chile flakes',
 'basil',
 'turbinado',
 'cinnamon',
 'cumin seed',
 'moong dal',
 'goat cheese',
 'picante sauce',
 'black pepper',
 'Tabasco Pepper Sauce',
 'lard',
 'ghee',
 'large egg whites',
 'hamburger buns',
 'liquid',
 'chili powder',
 'apples',
 'fresh salmon',
 'iceberg lettuce',
 'annatto oil',
 'red kidnei beans, rins and drain',
 'mustard oil',
 'cactus pad',
 'chile pepper',
 'saffron',
 'pasilla pepper',
 'grouper',
 'cooked rice',
 'gingersnap',
 'plain yogurt',
 'non-fat sour cream',
 'chicken leg quarters',
 'chopped onion',
 'sliced chicken',
 'instant yeast',
 'pecan pie',
 'string beans',
 'steel-cut oats',
 'sausage casings',
 'navy beans',
 'low sodium soy sauce',
 'mandarin oranges',
 'jaggery',
 'fat free milk',
 'luke warm water',
 'ketchup',
 'pepper',
 'almond flour',
 'fry mix',
 'condensed cream of mushroom soup',
 'silken tofu',
 'pork shoulder',
 'dried currants',
 'roasted peanuts',
 'spinach leaves',
 'cumin',
 'hazelnut oil',
 'cooked shrimp',
 'plantains',
 'ground cayenne pepper',
 'grana padano',
 'blood orange',
 'bourbon whiskey',
 'mixed spice',
 'fat free less sodium beef broth',
 'radicchio',
 'salted roast peanuts',
 'white rice',
 'calimyrna figs',
 'dark soy sauce',
 'unsalted butter',
 'kecap manis',
 'giardiniera',
 'soba noodles',
 'BertolliВ® Classico Olive Oil',
 'canola oil',
 'starchy potatoes',
 'cake flour',
 'udon',
 'Old El Paso Flour Tortillas',
 'baby bok choy',
 'heavy whipping cream',
 'rice flour',
 'lamb',
 'sage leaves',
 'juice',
 'dressing',
 'cooking oil',
 'green papaya',
 'butternut squash',
 'russet potatoes',
 'garlic paste',
 'Turkish bay leaves',
 'palm sugar',
 'chinese noodles',
 'chicken noodle soup',
 'octopuses',
 'freshly ground pepper',
 'unsalted dry roast peanuts',
 'cauliflower florets',
 'Philadelphia Cream Cheese',
 'minced ginger',
 'leg of lamb',
 'egg roll wrappers',
 'unflavored gelatin',
 'margarine',
 'garlic',
 'coconut cream',
 'pumpkin purГ©e',
 'pitted olives',
 'cooked ham',
 'finely chopped fresh parsley',
 'thyme sprigs',
 'caster',
 'flank steak',
 'arugula',
 'arame',
 'confit',
 'Boston lettuce',
 'lean ground beef',
 'wheat flour',
 'myzithra',
 'sun-dried tomatoes',
 'chorizo sausage',
 'sambal ulek',
 'shell-on shrimp',
 'medjool date',
 'andouille sausage',
 'apricot preserves',
 'sherry vinegar',
 'extra sharp cheddar cheese',
 'red pepper flakes',
 'granny smith apples',
 'sauce',
 'evaporated milk',
 'taco sauce',
 'shredded coconut',
 'mung bean sprouts',
 'orange blossom honey',
 'shrimp and crab boil seasoning',
 'sliced mushrooms',
 'romano cheese',
 'red beets',
 'tapioca starch',
 'chunky salsa',
 'boneless chop pork',
 'clove',
 'semolina',
 'green chile',
 'kaffir lime leaves',
 'low-fat natural yogurt',
 'coconut vinegar',
 'ranch dressing',
 'lemon slices',
 'crushed red pepper flakes',
 'ground cardamom',
 'sliced almonds',
 'peppercorns',
 'barley',
 'pickapeppa sauce',
 'dried chile peppers',
 'egg yolks',
 'sprinkles',
 'hot red pepper flakes',
 'steamed white rice',
 'chickpeas',
 'coconut sugar',
 'hoagie buns',
 'applewood smoked bacon',
 'fresh spinach',
 'finely chopped onion',
 'spinach',
 'parmigiano reggiano cheese',
 'fresh red chili',
 'olive oil flavored cooking spray',
 'guajillo',
 'cheese',
 'egg roll wraps',
 'yellow cake mix',
 'quickcooking grits',
 'lemon curd',
 'savoy cabbage',
 'ground cumin',
 'granulated garlic',
 'fire roasted diced tomatoes',
 'grape tomatoes',
 'crusty rolls',
 'vinaigrette dressing',
 'instant butterscotch pudding mix',
 'quail',
 'bread slices',
 'turnip greens',
 'shiitake',
 'balsamic vinegar',
 'green bell pepper, slice',
 'fat-free refried beans',
 'salted butter',
 'ciabatta',
 'brown cardamom',
 'green tomatoes',
 'sunflower oil',
 'fettuccine pasta',
 'tequila',
 'frozen peas',
 'basmati rice',
 'fat free yogurt',
 'yellow mustard',
 'coarse sea salt',
 'jicama',
 'fresh mushrooms',
 'reduced fat swiss cheese',
 'extra firm tofu',
 'shredded Monterey Jack cheese',
 'coffee beans',
 'Oscar Mayer Deli Fresh Smoked Ham',
 'roasted red peppers',
 'yellow squash',
 'green peas',
 'chipotle peppers',
 'sake',
 'Johnsonville Andouille Dinner Sausage',
 'boneless rib eye steaks',
 'arborio rice',
 'minced onion',
 'instant espresso powder',
 'edamame',
 'bacon slices',
 'asparagus spears',
 'bean threads',
 'toasted pecans',
 'bacon, crisp-cooked and crumbled',
 'lemongrass',
 'California bay leaves',
 'fennel seeds',
 'white sesame seeds',
 'ham',
 'chinese cabbage',
 'poblano peppers',
 'nori',
 'chocolate instant pudding',
 'tomatillo salsa',
 'margarita salt',
 'canned low sodium chicken broth',
 'ras el hanout',
 'crab meat',
 'black mustard seeds',
 'french bread',
 'pearl barley',
 'boneless beef short ribs',
 'grated nutmeg',
 'cornmeal',
 'smoked streaky bacon',
 'ground turmeric',
 'passata',
 'dough',
 'cheddar cheese',
 'pickled jalapeno peppers',
 'pizza crust',
 'Mexican beer',
 'coconut milk',
 'corn',
 'oven-ready lasagna noodles',
 'fresh ginger root',
 'butter lettuce',
 'pineapple preserves',
 'orange juice',
 'chili paste',
 'asian fish sauce',
 'salt',
 'fontina',
 'chopped celery',
 'red chili powder',
 'baby arugula',
 'capers',
 'whole milk',
 'Old El Pasoв„ў mild red enchilada sauce',
 'green mango',
 'mushrooms',
 'champagne vinegar',
 'angel food cake',
 'roasted tomatoes',
 'white corn tortillas',
 'grapeseed oil',
 'cooked white rice',
 'mustard greens',
 'natural yogurt',
 'boneless center cut pork chops',
 'pecans',
 'tomato purГ©e',
 'fine sea salt',
 'chicken breasts',
 'squabs',
 'greens',
 'mustard seeds',
 'egg bread',
 'andouille sausage links',
 'tomatillos',
 'Fuyu persimmons',
 'flax seed meal',
 'all-purpose flour',
 'pasta rotel',
 'large eggs',
 'shortening',
 'grated GruyГЁre cheese',
 'wish bone guacamol ranch dress',
 'salsa',
 'vegetable shortening',
 'slivered almonds',
 'chile sauce',
 'fresh lemon',
 'yukon gold potatoes',
 'rosemary sprigs',
 'jasmine rice',
 'margarita mix',
 'Italian parsley leaves',
 'chopped cilantro fresh',
 'dried bonito flakes',
 'lager beer',
 'garlic puree',
 'lime juice',
 'coleslaw',
 'rock sugar',
 'pistachios',
 'ground turkey',
 'urad dal',
 'roasted salted cashews',
 'softened butter',
 'seaweed',
 'boneless skinless chicken',
 'green cardamom',
 'wakame',
 'shredded carrots',
 'chicken livers',
 'tofu',
 'dipping sauces',
 'olive oil',
 'canned corn',
 'crushed red pepper',
 'demerara sugar',
 'pound cake',
 'sesame paste',
 'roasted garlic',
 'chopped pecans',
 'vegetable stock',
 'pasta',
 'green chilies',
 'organic sugar',
 'baby spinach',
 'coconut flour',
 'green peppercorns',
 'whole wheat pasta',
 'plum sauce',
 'sourdough baguette',
 'kidney beans',
 'whole peeled tomatoes',
 'fresh leav spinach',
 'cream cheese, soften',
 'low-fat mayonnaise',
 'dashi',
 'duck fat',
 'haricots verts',
 'extra-virgin olive oil',
 'rice',
 'gingerroot',
 'hominy',
 'gruyere cheese',
 'hibiscus',
 'green onions',
 'black salt',
 'milk',
 'black bean sauce',
 'light brown muscavado sugar',
 'ancho powder',
 'ginger paste',
 'chorizo spanish',
 'enchilada sauce',
 'chicken breast halves',
 'pickled carrots',
 'sugar',
 'instant espresso granules',
 'whole nutmegs',
 'spicy brown mustard',
 'dinner rolls',
 'fruit',
 'snow peas',
 'skinless chicken breasts',
 'chestnut flour',
 'lemon juice',
 'granulated sugar',
 'garbanzo beans',
 'Italian bread',
 'garlic cloves',
 'corn tortillas',
 'chipotle chile powder',
 'rice vinegar',
 'McCormick Parsley Flakes',
 'basil pesto sauce',
 'pork',
 'chuck roast',
 'tamari soy sauce',
 'lower sodium soy sauce',
 'saltines',
 'jack cheese',
 'white bread',
 'white vinegar',
 'melted butter',
 'pepitas',
 'penne',
 'light sour cream',
 'canned beef broth',
 'green beans',
 'bacon',
 'uncook medium shrimp, peel and devein',
 'sourdough loaf',
 'daikon',
 'curry',
 'ground beef',
 'vegetable juice',
 'sticky rice',
 'wheat',
 'lean steak',
 'bay leaf',
 'lower sodium chicken broth',
 'potato starch',
 'molasses',
 'italian seasoning mix',
 'zucchini',
 'bread crumb fresh',
 'lasagne',
 'ground red pepper',
 'water chestnuts, drained and chopped',
 'pork ribs',
 'orange bell pepper',
 'feta cheese',
 'dried black mushrooms',
 'creole mustard',
 'dashi kombu',
 'cremini mushrooms',
 'seasoning salt',
 'Japanese soy sauce',
 'diced onions',
 'fillets',
 'jambalaya rice mix',
 'chopped fresh sage',
 'low-fat buttermilk',
 'glutinous rice flour',
 'soft fresh goat cheese',
 'hoagie rolls',
 'fresh coriander',
 'fresh raspberries',
 'short rib',
 'red cabbage',
 'queso fresco',
 'ground pork',
 'pineapple juice',
 'black sesame seeds',
 'dried oregano',
 'vegetable oil cooking spray',
 'chopped green bell pepper',
 'white sandwich bread',
 'peanut butter',
 'red miso',
 'rhubarb',
 'taco seasoning',
 'Thai fish sauce',
 'curry powder',
 'colby cheese',
 'baguette',
 'instant espresso',
 'ice',
 'fat skimmed chicken broth',
 'hot bean paste',
 'skim milk',
 'round steaks',
 'fresh bay leaves',
 'minced garlic',
 'tomatoes',
 'wasabi paste',
 'ground allspice',
 'smoked gouda',
 'celery',
 'mayonaise',
 'cranberry sauce',
 'walnuts',
 'aged gouda',
 'vermicelli noodles',
 'dried red chile peppers',
 'frozen spinach',
 'rice cakes',
 'Gochujang base',
 'amchur',
 'hoisin sauce',
 'sweet onion',
 'frozen peas and carrots',
 'confectioners sugar',
 'jumbo shrimp',
 'cream sweeten whip',
 'onion tops',
 'fresh parsley',
 'saffron threads',
 'gluten-free hoisin sauce',
 'condensed cream of chicken soup',
 'dried chickpeas',
 'purple onion',
 'english cucumber',
 'veal cutlets',
 'whipping cream',
 'ground pepper',
 'peaches',
 'almonds',
 'salmon steaks',
 'chipotle',
 'hearts of palm',
 'white wine vinegar',
 'slaw mix',
 'biscuits',
 'toasted sesame seeds',
 'unsalted roasted peanuts',
 'celery ribs',
 'chili sauce',
 'toasted sesame oil',
 'free range egg',
 'naan',
 'dry vermouth',
 'wide rice noodles',
 'rum extract',
 'grits',
 'carbonated beverages',
 'sesame oil',
 'cod',
 'ground black pepper',
 'wax beans',
 'back bacon rashers',
 'asparagus tips',
 'corn oil',
 'corn starch',
 'pasta sheets',
 'herbs',
 'poblano chiles',
 'sweet potatoes',
 'horseradish',
 'arrowroot powder',
 'garlic powder',
 'fat-free cottage cheese',
 'reduced fat milk',
 'cabbage',
 'frozen corn',
 'large shrimp',
 'skirt steak',
 'frozen blueberries',
 'crushed tomatoes',
 'pesto sauce',
 'mixed greens',
 'fat free cream cheese',
 'fresh dill',
 'meat bones',
 'shredded cheese',
 'lime wedges',
 'marshmallow creme',
 'ricotta',
 'pita bread rounds',
 'cooking spray',
 'kielbasa',
 'grated lemon peel',
 'ground lamb',
 'vidalia onion',
 'manchego cheese',
 'dark rum',
 'low salt chicken broth',
 'allspice',
 'greek yogurt',
 'pickled jalapenos',
 'flat leaf parsley',
 'egg noodles',
 'aioli',
 'peeled fresh ginger',
 'mozzarella balls',
 'fresh veget',
 'miso paste',
 'orange juice concentrate',
 'fresh ginger',
 'onions',
 'napa cabbage leaves',
 'turnips',
 'wasabi',
 'green curry paste',
 'chicken thighs',
 'breakfast sausages',
 'Sriracha',
 'large garlic cloves',
 'fenugreek leaves',
 'pimentos',
 'pico de gallo',
 'hot sauce',
 'summer squash',
 'cauliflower flowerets',
 'bottled clam juice',
 'sweet chili sauce',
 'fresh tarragon',
 'peanuts',
 'napa cabbage',
 'condensed cheddar cheese soup',
 'reduced sodium tamari',
 'red lentils',
 'short-grain rice',
 'boneless chicken breast',
 'frozen broad beans',
 'pork tenderloin',
 'red bell pepper',
 'dill',
 'red beans',
 'sour cream',
 'plain whole-milk yogurt',
 'diced tomatoes',
 'active dry yeast',
 'hot pepper sauce',
 'artichokes',
 '(    oz.) tomato sauce',
 'chicken',
 'chili',
 'white rum',
 'fresh tomatoes',
 'baking soda',
 'cheese ravioli',
 'blackberries',
 'ricotta cheese',
 'chorizo',
 'rolls',
 'long grain white rice',
 'fresh rosemary',
 'dry white wine',
 'cream',
 'Corn Flakes Cereal',
 'adobo sauce',
 'genoa salami',
 'hass avocado',
 'double cream',
 'baby spinach leaves',
 'fingerling potatoes',
 'capicola',
 'red radishes',
 'pork loin chops',
 'baking powder',
 'smoked paprika',
 'kalamata',
 'swiss cheese',
 'dried cranberries',
 'salad',
 'puff pastry',
 'low sodium beef broth',
 'ground chicken',
 'low-fat sour cream',
 'corn chips',
 'golden delicious apples',
 'yellow corn meal',
 'chicken broth',
 'crusty bread',
 'Crystal Farms Butter',
 'coarse salt',
 'chives',
 'grated jack cheese',
 'polenta',
 'pecorino romano cheese',
 'red kidney beans',
 'sea scallops',
 'sundried tomato paste',
 'chuck',
 'spices',
 'chocolate morsels',
 'grilled chicken breasts',
 'basil leaves',
 'ground nutmeg',
 'club soda',
 'shiso',
 'carrots',
 'pappardelle',
 'zesty italian dressing',
 'orzo',
 'beer',
 'light brown sugar',
 'fat-free mayonnaise',
 'firm tofu',
 'roma tomatoes',
 'vegetables',
 'leaves',
 'chinese chives',
 'ancho chile pepper',
 'chinese black bean',
 'tuna',
 'mussels',
 'white miso',
 'paprika',
 'chees fresco queso',
 'chili paste with garlic',
 'broccoli rabe',
 'tahini',
 'reduced sodium soy sauce',
 'crema',
 'bacon drippings',
 'part-skim mozzarella cheese',
 'clams',
 'boneless skinless chicken breast halves',
 'berries',
 'ground cinnamon',
 'lemon grass',
 'wonton wrappers',
 'trout fillet',
 'salami',
 'mascarpone',
 'frozen whole kernel corn',
 'black peppercorns',
 'ginger juice',
 'crabmeat',
 'spring roll wrappers',
 'grated orange peel',
 'shredded sharp cheddar cheese',
 'kale leaves',
 'egg whites',
 'leeks',
 'rice noodles',
 'coriander powder',
 'yellow peppers',
 'peeled tomatoes',
 'lasagna noodles',
 'crema mexicana',
 'cayenne pepper',
 'taco seasoning mix',
 'white pepper',
 'rice wine',
 'fresh oregano',
 'mozzarella cheese',
 'dark brown sugar',
 'konbu',
 'Madeira',
 'kiwi',
 'dry sherry',
 'medium shrimp',
 'chili pepper',
 'tamarind',
 'chopped almonds',
 'torn romain lettuc leav',
 'medium eggs',
 'frosting',
 'fried garlic',
 'brewed tea',
 'butter',
 'steak',
 'sherry',
 'powdered sugar',
 'chiles',
 'swiss chard',
 'curry paste',
 'vidalia',
 'smoked trout',
 'fresh pineapple',
 'button mushrooms',
 'boiled ham',
 'diced celery',
 'pork chops',
 'jalapeno chilies',
 'marshmallows',
 'vermicelli',
 'refrigerated piecrusts',
 'fat free less sodium chicken broth',
 'parsley leaves',
 'cracked black pepper',
 'dried rosemary',
 'mint leaves',
 'apple cider vinegar',
 'broccoli',
 'chicken cutlets',
 'garlic salt',
 'Italian seasoned breadcrumbs',
 'florets',
 'bread flour',
 'flour tortillas',
 'provolone cheese',
 'grate lime peel',
 'tortilla chips',
 'baby potatoes',
 'red chile powder',
 'corn flour',
 'kashmiri chile',
 'caster sugar',
 'sirloin',
 'eau de vie',
 'cherry tomatoes',
 'garam masala',
 'lemon cucumber',
 'cayenne',
 'green bell pepper',
 'pecan halves',
 'ham hock',
 'hot chili',
 'shredded mozzarella cheese',
 'safflower oil',
 'tamarind paste',
 'brie cheese',
 'chili flakes',
 'chicken stock',
 'masa',
 'ground white pepper',
 'brown sugar',
 'frozen chopped spinach',
 'demi-glace',
 'cinnamon sugar',
 'tamarind pulp',
 'cocoa powder',
 'oyster sauce',
 'unsweetened coconut milk',
 'serrano',
 'potatoes',
 'lettuce',
 'apple cider',
 'prepared pizza crust',
 'wheat germ',
 'okra pods',
 'asparagus',
 'cream of tartar',
 'dry bread crumbs',
 'unsweetened cocoa powder',
 'whole milk ricotta cheese',
 'maida flour',
 'lemon olive oil',
 'dri leav thyme',
 'raspberries',
 'stuffing',
 'gari',
 'candied orange peel',
 'pears',
 'corn syrup',
 'sliced black olives',
 'coriander seeds',
 'penne pasta',
 'sweet and sour sauce',
 'canned black beans',
 'spaghetti',
 'cannellini beans',
 'diced bell pepper',
 'ice cubes',
 'prawns',
 'salt and ground black pepper',
 'boneless pork loin',
 'kale',
 'catfish',
 'pitted kalamata olives',
 'small red potato',
 'green cardamom pods',
 'vegetable broth',
 'Franks Hot Sauce',
 'natural peanut butter',
 'organic chicken',
 'beef stock',
 'bamboo shoots',
 'dried cherry',
 'almond extract',
 'dried basil',
 'fresh fava bean',
 'orzo pasta',
 'cardamom pods',
 'beansprouts',
 'fish fillets',
 'whole grain thin spaghetti',
 'cream of chicken soup',
 'double-acting baking powder',
 'pepperoni',
 'cooked brown rice',
 'crumbled blue cheese',
 'chile powder',
 'preserved lemon',
 'lamb neck fillets',
 'pork loin',
 'sesame seeds',
 'crab boil',
 'chunky peanut butter',
 'old bay seasoning',
 'cauliflower',
 'italian style rolls',
 'graham cracker crumbs',
 'condiments',
 'asiago',
 'tomato sauce',
 'cracker crumbs',
 'kimchi',
 'hazelnuts',
 'chocolate sauce',
 'lump crab meat',
 'vine ripened tomatoes',
 'plain flour',
 'fenugreek seeds',
 'mustard powder',
 'whole kernel corn, drain',
 'solid pack pumpkin',
 'caramel sauce',
 'kalonji',
 'golden brown sugar',
 'bean paste',
 'cardamom',
 'white wine',
 'gluten-free tamari',
 'eggplant',
 'english muffins, split and toasted',
 'shredded lettuce',
 'avocado',
 'maple syrup',
 'olive oil cooking spray',
 'filet',
 'chopped green chilies',
 'thyme leaves',
 'SargentoВ® Traditional Cut Shredded Mozzarella Cheese',
 'water',
 'vinegar',
 'epazote',
 'Guinness Lager',
 'espresso',
 'pitas',
 'chocolate bars',
 'serrano chile',
 'frozen pastry puff sheets',
 'boiled eggs',
 'harissa',
 'chestnuts',
 'lemon soda',
 'baking potatoes',
 'buckwheat noodles',
 'low sodium chicken broth',
 'chicken bones',
 'orange liqueur',
 'jamaican jerk season',
 'yoghurt',
 'sweet pepper',
 'boiling potatoes',
 'gnocchi',
 'refried beans',
 'blueberri preserv',
 'superfine sugar',
 'bell pepper',
 'rice paper',
 'freshly grated parmesan',
 'baking apples',
 'coarse kosher salt',
 'cucumber',
 'penne rigate',
 'brine-cured black olives',
 'Crystal Farms Shredded Gouda Cheese',
 'fresh asparagus',
 'pepper flakes',
 'pinenuts',
 'capsicum',
 'jam',
 'porcini',
 'bone-in chicken breasts',
 'water chestnuts',
 'yellow onion',
 'lime zest',
 'fresh chives',
 'monterey jack',
 'figs',
 'italian salad dressing mix',
 'Shaoxing wine',
 ...}

In [80]:
for ingredient in ingredient_list:
    df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)

C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)
C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3375928685.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[ingredient] = df['ingredients'].apply(lambda x: 1 if ingredient in x else 0)

In [81]:
df

,id,cuisine,ingredients,( oz.) tomato sauce,1% low-fat milk,2% reduced-fat milk,BertolliВ® Classico Olive Oil,Boston lettuce,California bay leaves,Corn Flakes Cereal,...,yellow mustard,yellow onion,yellow peppers,yellow squash,yellowtail,yoghurt,yukon gold potatoes,zesty italian dressing,zinfandel,zucchini
0,10259,greek,"[romaine lettuce, black olives, grape tomatoes...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,25693,southern_us,"[plain flour, ground pepper, salt, tomatoes, g...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,20130,filipino,"[eggs, pepper, salt, mayonaise, cooking oil, g...",0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
3,22213,indian,"[water, vegetable oil, wheat, salt]",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,13162,indian,"[black pepper, shallots, cornflour, cayenne pe...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1121,chinese,"[ground pepper, garlic, safflower oil, green o...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
496,18376,italian,"[penne, garlic, eggplant, lemon juice, olive o...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
497,17815,italian,"[cold water, dry white wine, fish fillets, cho...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
498,32878,southern_us,"[water, cajun seasoning, yellow onion, shrimp,...",0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
499,24410,british,"[mint, large eggs, heavy cream, berries, groun...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [82]:
# Создаём новый столбец с количеством ингредиентов в каждом рецепте
df['ingredients_count'] = df['ingredients'].apply(len)

# Выведем первые несколько строк для проверки
print(df[['ingredients', 'ingredients_count']].head())

                                         ingredients  ingredients_count
0  [romaine lettuce, black olives, grape tomatoes...                  9
1  [plain flour, ground pepper, salt, tomatoes, g...                 11
2  [eggs, pepper, salt, mayonaise, cooking oil, g...                 12
3                [water, vegetable oil, wheat, salt]                  4
4  [black pepper, shallots, cornflour, cayenne pe...                 20

C:\Users\ykarabekov\AppData\Local\Temp\ipykernel_21216\3427877432.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df['ingredients_count'] = df['ingredients'].apply(len)

In [83]:
df

,id,cuisine,ingredients,( oz.) tomato sauce,1% low-fat milk,2% reduced-fat milk,BertolliВ® Classico Olive Oil,Boston lettuce,California bay leaves,Corn Flakes Cereal,...,yellow onion,yellow peppers,yellow squash,yellowtail,yoghurt,yukon gold potatoes,zesty italian dressing,zinfandel,zucchini,ingredients_count
0,10259,greek,"[romaine lettuce, black olives, grape tomatoes...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,9
1,25693,southern_us,"[plain flour, ground pepper, salt, tomatoes, g...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,11
2,20130,filipino,"[eggs, pepper, salt, mayonaise, cooking oil, g...",0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,12
3,22213,indian,"[water, vegetable oil, wheat, salt]",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,4
4,13162,indian,"[black pepper, shallots, cornflour, cayenne pe...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1121,chinese,"[ground pepper, garlic, safflower oil, green o...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,9
496,18376,italian,"[penne, garlic, eggplant, lemon juice, olive o...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,8
497,17815,italian,"[cold water, dry white wine, fish fillets, cho...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,8
498,32878,southern_us,"[water, cajun seasoning, yellow onion, shrimp,...",0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,19
499,24410,british,"[mint, large eggs, heavy cream, berries, groun...",0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,17

In [84]:
len(all_ingredients)

1318

In [85]:
ids = df['id'].drop_duplicates().tolist()

# Создаем список ингредиентов — все колонки, кроме служебных
ingredients = [col for col in df.columns if col not in ['cuisine', 'id', 'ingredients']]

def make_list(row):
    # Выбираем только те ингредиенты, у которых значение в этой строке != 0
    present_ingredients = [ingredient for ingredient in ingredients if row[ingredient] != 0]
    return present_ingredients


# Создаём пустой список для хранения итоговой структуры
new_recipes = [] 
# Организуем цикл с параметром current_id
for current_id in ids: 
    cuisine = df[df['id'] == current_id]['cuisine'].iloc[0] 
    current_ingredients = make_list(df[df['id'] == current_id].iloc[0]) 
    current_recipe = {'cuisine': cuisine, 'id': int(current_id), 'ingredients': current_ingredients} 
    new_recipes.append(current_recipe)


# Импорт модуля json
import json 
# Функция dumps() модуля json сериализирует объект Python в строку формата JSON. 
new_recipes = json.dumps(new_recipes) 

# Откроем файл new_recipes.json для записи
with open("data/new_recipes.json", "w") as write_file: 
    # Записываем содержимое подготовленные данные в файл
    write_file.write(new_recipes)

In [86]:
# Импортируем модуль ElementTree
import xml.etree.ElementTree as ET

In [87]:
tree = ET.parse('data/menu.xml')

In [88]:
root = tree.getroot()
display(root)

In [89]:
children = list(root)
print(len(children))

2

In [90]:
print(root[0][2].tag)

class

In [91]:
for dish in root:
    for param in dish:
        print(dish.attrib['name'], param.tag, param.text)
    print()

Кура price 40
Кура weight 300
Кура class Мясо

Греча price 20
Греча weight 200
Греча class Крупа

In [92]:
column_names = ['name', 'price', 'weight', 'class']
df_list = []

for dish in root:
    row = [dish.attrib['name'], dish[0].text, dish[1].text, dish[2].text]
    df_list.append(row)

df = pd.DataFrame(df_list, columns=column_names)
display(df)

    name price weight  class
0   Кура    40    300   Мясо
1  Греча    20    200  Крупа

In [97]:
import requests # Импортируем библиотеку requests
url = 'https://www.cbr-xml-daily.ru/daily_json.js' # Определяем значение URL страницы для запроса
response = requests.get(url, verify=False) # Делаем GET-запрос к ресурсу и результат ответа сохраняем в переменной response

In [94]:
from pprint import pprint # Импортируем функцию pprint()
import json # Импортируем модуль json
currencies = response.json() # Применяем метод json()
pprint(currencies) # Выводим результат на экран

{'Date': '2025-07-03T11:30:00+03:00',
 'PreviousDate': '2025-07-02T11:30:00+03:00',
 'PreviousURL': '//www.cbr-xml-daily.ru/archive/2025/07/02/daily_json.js',
 'Timestamp': '2025-07-02T18:00:00+03:00',
 'Valute': {'AED': {'CharCode': 'AED',
                    'ID': 'R01230',
                    'Name': 'Дирхам ОАЭ',
                    'Nominal': 1,
                    'NumCode': '784',
                    'Previous': 21.3528,
                    'Value': 21.417},
            'AMD': {'CharCode': 'AMD',
                    'ID': 'R01060',
                    'Name': 'Армянских драмов',
                    'Nominal': 100,
                    'NumCode': '051',
                    'Previous': 20.3514,
                    'Value': 20.4556},
            'AUD': {'CharCode': 'AUD',
                    'ID': 'R01010',
                    'Name': 'Австралийский доллар',
                    'Nominal': 1,
                    'NumCode': '036',
                    'Previous': 51.5913,
                    'Value': 51.7307},
            'AZN': {'CharCode': 'AZN',
                    'ID': 'R01020A',
                    'Name': 'Азербайджанский манат',
                    'Nominal': 1,
                    'NumCode': '944',
                    'Previous': 46.1283,
                    'Value': 46.2671},
            'BGN': {'CharCode': 'BGN',
                    'ID': 'R01100',
                    'Name': 'Болгарский лев',
                    'Nominal': 1,
                    'NumCode': '975',
                    'Previous': 46.9907,
                    'Value': 47.4941},
            'BRL': {'CharCode': 'BRL',
                    'ID': 'R01115',
                    'Name': 'Бразильский реал',
                    'Nominal': 1,
                    'NumCode': '986',
                    'Previous': 14.3707,
                    'Value': 14.4298},
            'BYN': {'CharCode': 'BYN',
                    'ID': 'R01090B',
                    'Name': 'Белорусский рубль',
                    'Nominal': 1,
                    'NumCode': '933',
                    'Previous': 26.4649,
                    'Value': 26.5194},
            'CAD': {'CharCode': 'CAD',
                    'ID': 'R01350',
                    'Name': 'Канадский доллар',
                    'Nominal': 1,
                    'NumCode': '124',
                    'Previous': 57.4786,
                    'Value': 57.6515},
            'CHF': {'CharCode': 'CHF',
                    'ID': 'R01775',
                    'Name': 'Швейцарский франк',
                    'Nominal': 1,
                    'NumCode': '756',
                    'Previous': 99.3389,
                    'Value': 99.2479},
            'CNY': {'CharCode': 'CNY',
                    'ID': 'R01375',
                    'Name': 'Юань',
                    'Nominal': 1,
                    'NumCode': '156',
                    'Previous': 10.9384,
                    'Value': 10.9465},
            'CZK': {'CharCode': 'CZK',
                    'ID': 'R01760',
                    'Name': 'Чешских крон',
                    'Nominal': 10,
                    'NumCode': '203',
                    'Previous': 37.5134,
                    'Value': 37.5365},
            'DKK': {'CharCode': 'DKK',
                    'ID': 'R01215',
                    'Name': 'Датская крона',
                    'Nominal': 1,
                    'NumCode': '208',
                    'Previous': 12.3183,
                    'Value': 12.4506},
            'EGP': {'CharCode': 'EGP',
                    'ID': 'R01240',
                    'Name': 'Египетских фунтов',
                    'Nominal': 10,
                    'NumCode': '818',
                    'Previous': 15.8582,
                    'Value': 15.9404},
            'EUR': {'CharCode': 'EUR',
                    'ID': 'R01239',
                    'Name': 'Евро',
                    'Nominal': 1,
                    'NumCode': '978',
                    'Previous': 92.744,
                    'Value': 92.6774},
            'GBP': {'CharCode': 'GBP',
                    'ID': 'R01035',
                    'Name': 'Фунт стерлингов',
                    'Nominal': 1,
                    'NumCode': '826',
                    'Previous': 107.4563,
                    'Value': 107.8976},
            'GEL': {'CharCode': 'GEL',
                    'ID': 'R01210',
                    'Name': 'Лари',
                    'Nominal': 1,
                    'NumCode': '981',
                    'Previous': 28.8016,
                    'Value': 28.901},
            'HKD': {'CharCode': 'HKD',
                    'ID': 'R01200',
                    'Name': 'Гонконгский доллар',
                    'Nominal': 1,
                    'NumCode': '344',
                    'Previous': 10.0074,
                    'Value': 10.0375},
            'HUF': {'CharCode': 'HUF',
                    'ID': 'R01135',
                    'Name': 'Форинтов',
                    'Nominal': 100,
                    'NumCode': '348',
                    'Previous': 23.1958,
                    'Value': 23.2079},
            'IDR': {'CharCode': 'IDR',
                    'ID': 'R01280',
                    'Name': 'Рупий',
                    'Nominal': 10000,
                    'NumCode': '360',
                    'Previous': 48.3138,
                    'Value': 48.5758},
            'INR': {'CharCode': 'INR',
                    'ID': 'R01270',
                    'Name': 'Индийских рупий',
                    'Nominal': 100,
                    'NumCode': '356',
                    'Previous': 91.5908,
                    'Value': 91.786},
            'JPY': {'CharCode': 'JPY',
                    'ID': 'R01820',
                    'Name': 'Иен',
                    'Nominal': 100,
                    'NumCode': '392',
                    'Previous': 54.5935,
                    'Value': 54.773},
            'KGS': {'CharCode': 'KGS',
                    'ID': 'R01370',
                    'Name': 'Сомов',
                    'Nominal': 100,
                    'NumCode': '417',
                    'Previous': 89.6719,
                    'Value': 89.9417},
            'KRW': {'CharCode': 'KRW',
                    'ID': 'R01815',
                    'Name': 'Вон',
                    'Nominal': 1000,
                    'NumCode': '410',
                    'Previous': 57.933,
                    'Value': 58.1502},
            'KZT': {'CharCode': 'KZT',
                    'ID': 'R01335',
                    'Name': 'Тенге',
                    'Nominal': 100,
                    'NumCode': '398',
                    'Previous': 15.0909,
                    'Value': 15.1464},
            'MDL': {'CharCode': 'MDL',
                    'ID': 'R01500',
                    'Name': 'Молдавских леев',
                    'Nominal': 10,
                    'NumCode': '498',
                    'Previous': 46.6297,
                    'Value': 47.1171},
            'NOK': {'CharCode': 'NOK',
                    'ID': 'R01535',
                    'Name': 'Норвежских крон',
                    'Nominal': 10,
                    'NumCode': '578',
                    'Previous': 77.6594,
                    'Value': 78.425},
            'NZD': {'CharCode': 'NZD',
                    'ID': 'R01530',
                    'Name': 'Новозеландский доллар',
                    'Nominal': 1,
                    'NumCode': '554',
                    'Previous': 47.686,
                    'Value': 47.9317},
            'PLN': {'CharCode': 'PLN',
                    'ID': 'R01565',
                    'Name': 'Злотый',
                    'Nominal': 1,
                    'NumCode': '985',
                    'Previous': 21.8252,
                    'Value': 21.7938},
            'QAR': {'CharCode': 'QAR',
                    'ID': 'R01355',
                    'Name': 'Катарский риал',
                    'Nominal': 1,
                    'NumCode': '634',
                    'Previous': 21.5434,
                    'Value': 21.6082},
            'RON': {'CharCode': 'RON',
                    'ID': 'R01585F',
                    'Name': 'Румынский лей',
                    'Nominal': 1,
                    'NumCode': '946',
                    'Previous': 18.2546,
                    'Value': 18.2768},
            'RSD': {'CharCode': 'RSD',
                    'ID': 'R01805F',
                    'Name': 'Сербских динаров',
                    'Nominal': 100,
                    'NumCode': '941',
                    'Previous': 78.9037,
                    'Value': 79.1951},
            'SEK': {'CharCode': 'SEK',
                    'ID': 'R01770',
                    'Name': 'Шведских крон',
                    'Nominal': 10,
                    'NumCode': '752',
                    'Previous': 82.4528,
                    'Value': 83.2426},
            'SGD': {'CharCode': 'SGD',
                    'ID': 'R01625',
                    'Name': 'Сингапурский доллар',
                    'Nominal': 1,
                    'NumCode': '702',
                    'Previous': 61.6107,
                    'Value': 61.7815},
            'THB': {'CharCode': 'THB',
                    'ID': 'R01675',
                    'Name': 'Батов',
                    'Nominal': 10,
                    'NumCode': '764',
                    'Previous': 24.1442,
                    'Value': 24.2288},
            'TJS': {'CharCode': 'TJS',
                    'ID': 'R01670',
                    'Name': 'Сомони',
                    'Nominal': 10,
                    'NumCode': '972',
                    'Previous': 79.5848,
                    'Value': 79.7684},
            'TMT': {'CharCode': 'TMT',
                    'ID': 'R01710A',
                    'Name': 'Новый туркменский манат',
                    'Nominal': 1,
                    'NumCode': '934',
                    'Previous': 22.4052,
                    'Value': 22.4726},
            'TRY': {'CharCode': 'TRY',
                    'ID': 'R01700J',
                    'Name': 'Турецких лир',
                    'Nominal': 10,
                    'NumCode': '949',
                    'Previous': 19.7146,
                    'Value': 19.7578},
            'UAH': {'CharCode': 'UAH',
                    'ID': 'R01720',
                    'Name': 'Гривен',
                    'Nominal': 10,
                    'NumCode': '980',
                    'Previous': 18.7517,
                    'Value': 18.8115},
            'USD': {'CharCode': 'USD',
                    'ID': 'R01235',
                    'Name': 'Доллар США',
                    'Nominal': 1,
                    'NumCode': '840',
                    'Previous': 78.4181,
                    'Value': 78.654},
            'UZS': {'CharCode': 'UZS',
                    'ID': 'R01717',
                    'Name': 'Узбекских сумов',
                    'Nominal': 10000,
                    'NumCode': '860',
                    'Previous': 61.771,
                    'Value': 62.049},
            'VND': {'CharCode': 'VND',
                    'ID': 'R01150',
                    'Name': 'Донгов',
                    'Nominal': 10000,
                    'NumCode': '704',
                    'Previous': 31.2946,
                    'Value': 31.3738},
            'XDR': {'CharCode': 'XDR',
                    'ID': 'R01589',
                    'Name': 'СДР (специальные права заимствования)',
                    'Nominal': 1,
                    'NumCode': '960',
                    'Previous': 107.7465,
                    'Value': 108.4481},
            'ZAR': {'CharCode': 'ZAR',
                    'ID': 'R01810',
                    'Name': 'Рэндов',
                    'Nominal': 10,
                    'NumCode': '710',
                    'Previous': 44.5616,
                    'Value': 44.4931}}}

In [98]:
from bs4 import BeautifulSoup # Импортируем библиотеку BeautifulSoup
url = 'https://nplus1.ru/news/2021/10/11/econobel2021' # Определяем адрес страницы
response = requests.get(url, verify=False) # Выполняем GET-запрос, содержимое ответа присваивается переменной response
page = BeautifulSoup(response.text, 'html.parser') # Создаём объект BeautifulSoup, указывая html-парсер
print(page.title) # Получаем тег title, отображающийся на вкладке браузера
print(page.title.text) # Выводим текст из полученного тега, который содержится в атрибуте text

<title>Премию Нобеля по экономике присудили за исследования экономики труда и причинно-следственных связей</title>
Премию Нобеля по экономике присудили за исследования экономики труда и причинно-следственных связей

In [99]:
print(page.find('h1').text)

            Премию Нобеля по экономике присудили за исследования экономики труда и причинно-следственных связей

In [100]:
import requests
from bs4 import BeautifulSoup

def wiki_header(url):
    response = requests.get(url, verify = False)
    soup = BeautifulSoup(response.content, 'html.parser')
    header = soup.find('h1')
    return header.text.strip() if header else None

In [101]:
print(page.find('div').text) # Выводим содержимое атрибута text тега div

In [102]:
print(page.find('div', class_='n1_material text-18').text) # Выводим содержимое атрибута text тега div класса n1_material text-18

Премия Шведского национального банка по экономическим наукам памяти Альфреда Нобеля за 2021 год присуждена Дэвиду Карду (David Card) за его вклад в эмпирические исследования экономики рынка труда, а также Джошуа Энгристу (Joshua Angrist) и Гвидо Имбенсу (Guido Imbens) за их вклад в методологию анализа причинно-следственных связей. Прямая трансляция церемонии объявления лауреатов шла на официальном сайте Нобелевской премии.

In [103]:
print(page.find('div', class_='n1_material').text)

Премия Шведского национального банка по экономическим наукам памяти Альфреда Нобеля за 2021 год присуждена Дэвиду Карду (David Card) за его вклад в эмпирические исследования экономики рынка труда, а также Джошуа Энгристу (Joshua Angrist) и Гвидо Имбенсу (Guido Imbens) за их вклад в методологию анализа причинно-следственных связей. Прямая трансляция церемонии объявления лауреатов шла на официальном сайте Нобелевской премии.

In [104]:
print(page.find('div', class_='n1_material text-18').text)

Премия Шведского национального банка по экономическим наукам памяти Альфреда Нобеля за 2021 год присуждена Дэвиду Карду (David Card) за его вклад в эмпирические исследования экономики рынка труда, а также Джошуа Энгристу (Joshua Angrist) и Гвидо Имбенсу (Guido Imbens) за их вклад в методологию анализа причинно-следственных связей. Прямая трансляция церемонии объявления лауреатов шла на официальном сайте Нобелевской премии.

In [105]:
# Выводим на экран содержимое атрибута text тега a с классом "relative"
print(page.find('a', class_= "relative").text)

11.10.21

In [108]:
url = 'https://en.wikipedia.org/wiki/List_of_programming_languages' # Задаём адрес ресурса
response = requests.get(url, verify = False) # Делаем GET-запрос к ресурсу
links = page.find_all('a') # Ищем все ссылки на странице и сохраняем в переменной links в виде списка
print(len(links)) # Выводим количество найденных ссылок

966

In [109]:
print([link.text for link in links[500:510]]) # Выводим ссылки с 500 по 509 включительно

['MAD', 'MAD/I', 'Magik', 'Magma', 'Maple', 'MAPPER', 'MARK-IV', 'Mary', 'MATLAB', 'MASM Microsoft Assembly x86']